# Sis1 = Sistema()
# pac1 = Paciente()
# pac1.asignarNombre(nombre = 'JUAN ESTEBAN HINCAPIE')
# pac1.asignarCedula(cedula = 1041440201)
# marcapaso1 = Marcapasos()
# marcapaso1.asignarConexion(c= 'alambrica')
# marcapaso1.asignarFRECUENCIA(c=200)
# marcapaso1.asignarNumElectrodos(c=30)

# implanteCadera1 =ImplanteCadera()
# implanteCadera1.asignarMaterial(c='Hierro')
# implanteCadera1.asignarForma(c='redondeada')

# pac2 = Paciente()
# pac2.asignarNombre(nombre = 'JUAN ESTEBAN HINCAPIE')
# pac2.asignarCedula(cedula = 1041440201)
# marcapaso1 = Marcapasos()
# marcapaso1.asignarConexion(c= 'alambrica')
# marcapaso1.asignarFRECUENCIA(c=200)
# marcapaso1.asignarNumElectrodos(c=30)

# implanteCadera1 =ImplanteCadera()
# implanteCadera1.asignarMaterial(c='Hierro')
# implanteCadera1.asignarForma(c='redondeada')

# pac2.asignarImplantes(marcapaso1)
# pac2.asignarImplantes(implanteCadera1)

# Sis1.ingresarPaciente(pac1)
# Sis1.ingresarPaciente(pac2)

# print(Sis1.verPaciente(1041440201))